#+Title: Grekiska 1, Lektion 10
#+Author: Jonas Ransjö
#+Email: jonas.ransjo@lingfil.uu.se
#+LANGUAGE: sv
#+INCLUDE: ~/.emacs.d/org-templates/reveal.org
#+OPTIONS: toc:1
#+REVEAL_EXTRA_CSS: /slides/css/greek.css
#+REVEAL_EXTRA_CSS: /slides/css/lektion10.css


* Afrodite och Hermes
\\
#+BEGIN_HTML
<div style="text-align: left;">
<p>ΑΦΡΟΔΙΤΗ</p>
<p class="fragment">οὐκοῦν, ὦ Ἡερμῆ, κἀμὲ λαβῶν ἐν τοῖς προέδροις που κάθιζε· χρυσῆ γάρ εἰμι.</p>
<p class="fragment">καὶ μὴν ἀξιόπιστόν σοι μάρτυρα τὸν Ὅμηρον παρέξομαι ἄνω καὶ κάτω τῶν ῥαψῳδιῶν χρυσῆν με τὴν Ἀφροδίτην εἶναι λέγοντα.</p>

</div>
#+END_HTML
#+REVEAL: split
#+BEGIN_HTML
<div style="text-align: left">
<p>ΕΡΜΗΣ</p>
<p class="fragment">καὶ γὰρ τὸν Ἀπόλλω ὁ αὐτὸς πολύχρυσον εἶναι ἔφη καὶ πλούσιον·</p>
<p class="fragment">ἀλλὰ νῦν ὄψει κἀκεῖνον ἐν τοῖς ζευγίταις που καθήμενον,</p>
<p class="fragment">ἀπεστεφανωμένον τε ὑπὸ τῶν λῃστῶν καὶ τοὺς κόλλοπας τῆς κιθάρας περισεσυλημένον.</p>
<p class="fragment">ὥστε ἀγάπα καὶ σὺ μὴ πάνυ ἐν τῷ θητικῷ ἐκκλησιάζουσα.</p>
</div>
#+END_HTML
#+REVEAL: split
#+BEGIN_HTML
<div style="text-align: left">
<p>ΚΟΛΟΣΣΟΣ ΡΟΔΙΩΝ</p>
<p class="fragment">ἐμοὶ δὲ τίς ἂν ἐρίσαι τολμήσειεν Ἡλίῳ τε ὄντι καὶ τηλικούτῳ τὸ μέγεθος;</p>
</div>
#+END_HTML

* Korpen och Räven

#+BEGIN_HTML
<div style="text-align: left">
<p class="fragment">καθήμενος ἐπὶ δένδρῳ, ὁ κόραξ ἤσθιεν κρεάδιον.</p>
<p class="fragment">ἡ δὲ ἀλώπηξ ἰδὼν αὐτὸν, ἐβούλετο τὸ κρεάδιον ἁρπάσαι.</p>
<p class="fragment">δολερὸς δὲ οὖσα, τὸν κόρακα ἐπῄνεει.</p>
<p class="fragment">"καλὸς εἶ," ἔφη, "καί σε θαυμάζω, ἀλλὰ κακόν ἐστί σε φωνὴν οὐκ ἔχειν."</p>
<p class="fragment">ὁ δὲ κόραξ, "πῶς λέγεις," ἔφη, "ὅτι φωνὴν οὐκ ἔχω;"</p>
<p class="fragment">καὶ ταῦτα λέγων, κατέβαλε εὐθὺς τὸ κρεάδιον ἀπὸ τοῦ στόματος.</p>
<p class="fragment">ἡ δὲ ἀλώπηξ ἁρπάσασα τὸ κρεάδιον, ἔλεγεν·</p>
<p class="fragment">"ὦ κόραξ, φωνὴν μὲν ἔχεις, νοῦν δὲ οὔ."</p>
</div>
#+END_HTML
